name: test

'on':
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name'. Reference:
      # https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/9
    - '**:**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir-version: ['1.10', '1.11']
        otp-version: ['22', '23']
        include:
          - elixir-version: '1.6'
            otp-version: '20'
          - elixir-version: '1.7'
            otp-version: '20'
          - elixir-version: '1.8'
            otp-version: '21'
          - elixir-version: '1.9'
            otp-version: '21'
    continue-on-error: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    - name: Get deps cache
      uses: actions/cache@v1
      with:
        path: deps/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-

    - name: Get build cache
      uses: actions/cache@v1
      with:
        path: _build/test/
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile

    - name: Run linters
      run: |
        mix format --check-formatted
        mix credo --strict

    - name: Run Tests
      run: mix coveralls.github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
